// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCCN2J7OsUpd8WCiFLYYEy_-fjDol2scBM',
    appId: '1:652644769095:web:6681f254b6271444d00062',
    messagingSenderId: '652644769095',
    projectId: 'mobileappproject-a33a9',
    authDomain: 'mobileappproject-a33a9.firebaseapp.com',
    storageBucket: 'mobileappproject-a33a9.firebasestorage.app',
    measurementId: 'G-Q837Y5ESN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAzmbjalu6liZAC9Q_bG7iUDCNvMwHizw8',
    appId: '1:652644769095:android:e6e8384f008268ccd00062',
    messagingSenderId: '652644769095',
    projectId: 'mobileappproject-a33a9',
    storageBucket: 'mobileappproject-a33a9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKsPJHeyBTzK0GRGFfHsGmTQumggdlE30',
    appId: '1:652644769095:ios:ab2ebf5ba811227dd00062',
    messagingSenderId: '652644769095',
    projectId: 'mobileappproject-a33a9',
    storageBucket: 'mobileappproject-a33a9.firebasestorage.app',
    iosClientId: '652644769095-2sh5r6nq62h4qipjuppmb8v3qi23l64t.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKsPJHeyBTzK0GRGFfHsGmTQumggdlE30',
    appId: '1:652644769095:ios:ab2ebf5ba811227dd00062',
    messagingSenderId: '652644769095',
    projectId: 'mobileappproject-a33a9',
    storageBucket: 'mobileappproject-a33a9.firebasestorage.app',
    iosClientId: '652644769095-2sh5r6nq62h4qipjuppmb8v3qi23l64t.apps.googleusercontent.com',
    iosBundleId: 'com.example.project',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCCN2J7OsUpd8WCiFLYYEy_-fjDol2scBM',
    appId: '1:652644769095:web:30094e8fe18bb569d00062',
    messagingSenderId: '652644769095',
    projectId: 'mobileappproject-a33a9',
    authDomain: 'mobileappproject-a33a9.firebaseapp.com',
    storageBucket: 'mobileappproject-a33a9.firebasestorage.app',
    measurementId: 'G-GFY88GPK1N',
  );

}